#!/bin/bash

# import colors
# source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEMS_DIR="$HOME/.config/sketchybar/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar -m --bar \
		height=32 \
		position=top \
		padding_left=0 \
		padding_right=0 \
		color=0xff3b4252 \
		shadow=off \
		topmost=off

# sketchybar --bar position=top \
#            height=32 \
#            color=0xff000000 \
#            shadow=on \
#            sticky=on \
#            padding_left=0 \
#            padding_right=0 \
#            y_offset=4 \
#            margin=4 \
#            blur_radius=0 \
#            corner_radius=8

# sketchybar --bar position=top height=35 blur_radius=30 color=0x00000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           popup.align=left \
           popup.background.color=0xff000000 \
           popup.background.corner_radius=12 \
           popup.background.border_width=1 \
           popup.background.border_color=0x50b0b8cc \
           script="$HOME/Documents/tracker/plugins/apple_menu.sh" \
           --subscribe chevron mouse.clicked \
           --add item front_app center \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" display=1 \
           --subscribe front_app front_app_switched \
           --add item front_app_external center \
           --set front_app_external icon.drawing=off script="$PLUGIN_DIR/front_app.sh" display=2 \
           --subscribe front_app_external front_app_switched

##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=30 script="$PLUGIN_DIR/clock.sh" \
           icon.font="Hack Nerd Font:Bold:14.0" \
           label.font="Hack Nerd Font:Bold:14.0" \
           icon.padding_left=8 \
           label.padding_right=8 \
           click_script="open -a 'Calendar'" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change mouse.clicked \
           --add slider volume_slider right 100 \
           --set volume_slider \
           icon.drawing=off \
           label.drawing=off \
           slider.highlight_color=0xff5ad4e6 \
           slider.width=0 \
           slider.background.height=6 \
           slider.background.corner_radius=3 \
           slider.background.color=0x4dffffff \
           slider.knob.string=􀀁 \
           slider.knob.drawing=on \
           script="$PLUGIN_DIR/volume_slider.sh" \
           --subscribe volume_slider mouse.clicked \
           --add item battery right \
           --set battery update_freq=180 script="$PLUGIN_DIR/battery.sh" background.padding_left=5 popup.align=center \
           --subscribe battery routine system_woke power_source_change mouse.clicked \
           --add item battery_time popup.battery \
           --set battery_time icon="Time remaining:" icon.width=100 label="No estimate" label.width=100

source "$ITEMS_DIR/slack.sh"
source "$ITEMS_DIR/keyboard.sh"

sketchybar --add item apple_restart popup.chevron \
           --set apple_restart \
           icon="󰜉" \
           icon.width=28 \
           label="Restart" \
           label.width=120 \
           label.align=left \
           click_script="$HOME/Documents/tracker/plugins/apple_restart.sh"

sketchybar --add item apple_shutdown popup.chevron \
           --set apple_shutdown \
           icon="" \
           icon.width=28 \
           label="Shut Down" \
           label.width=120 \
           label.align=left \
           click_script="$HOME/Documents/tracker/plugins/apple_shutdown.sh"

sketchybar --add graph cpu right 42 \
           --set cpu \
           update_freq=2 \
           graph.color=0xff5ad4e6 \
           graph.fill_color=0x335ad4e6 \
           background.height=22 \
           background.drawing=on \
           icon="" \
           icon.color=0xff5ad4e6 \
           label.width=32 \
           script="$HOME/Documents/tracker/plugins/cpu.sh" \
           --subscribe cpu mouse.clicked

# Rounded widget groups inspired by flameberry/Dotfiles.
# GROUP_BG=(
#   background.color=0xff000000
#   background.corner_radius=16
#   background.height=28
#   background.padding_left=8
#   background.padding_right=8
#   background.shadow.drawing=on
#   background.shadow.color=0x80000000
#   background.shadow.distance=2
#   background.shadow.blur_radius=4
# )

sketchybar --add bracket app_group front_app
          #  --set app_group "${GROUP_BG[@]}"
sketchybar --add bracket app_group_external front_app_external
          #  --set app_group_external "${GROUP_BG[@]}"

sketchybar --add bracket right_widgets clock volume volume_slider battery slack keyboard cpu
          #  --set right_widgets "${GROUP_BG[@]}"
sketchybar --set right_widgets background.padding_right=18

sketchybar --hotload on
sketchybar --update
